version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8080"
    environment:
      - AWS_ACCESS_KEY_ID=AKIA3ARSXWIEQ3TUVFAI
      - AWS_SECRET_ACCESS_KEY=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
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  database:
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=Kurmanalieva93
      - MYSQL_DATABASE=awsDB
