---
- name: Install database, Log in to database Hub, Pull database Image, and Run database Container
  hosts: my_ec2_instance
  become: true
  gather_facts: true

  tasks:
    - name: Install prerequisites for database on Amazon Linux
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - docker

    - name: Start database service on Amazon Linux
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to database Hub
      docker_login:
        username: "{{ secrets.DOCKERHUB_USERNAME }}"
        password: "{{ secrets.DOCKERHUB_TOKEN }}"
        registry_url: https://index.docker.io/v1/
      when: secrets.DOCKERHUB_USERNAME is defined and secrets.DOCKERHUB_TOKEN is defined

    - name: Pull database image
      docker_image:
        name: "mkurmanalieva/frontend:latest"
        source: pull

    - name: Run database container
      docker_container:
        name: mycontainer
        image: "mkurmanalieva/frontend:latest"
        ports:
          - "8080:8080"
        volumes:
          - /home/ec2-user/Web:/usr/local/apache2/htdocs/
        restart_policy: always
        state: started
      register: status

    - name: Check container status
      debug:
        var: status
