---
- name: Install Docker on Target Host
  hosts: my_ec2_instance
  become: true


  tasks:
    - name: Start Docker service
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ secrets.DOCKERHUB_USERNAME }}"
        password: "{{ secrets.DOCKERHUB_TOKEN }}"
        registry_url: https://index.docker.io/v1/
      when: secrets.DOCKERHUB_USERNAME is defined and secrets.DOCKERHUB_TOKEN is defined


    - name: Stop all Docker containers
      command: docker stop $(docker ps -a -q)
      ignore_errors: true

    - name: Remove all Docker containers
      command: docker rm $(docker ps -a -q)
      ignore_errors: true

    - name: Pull Docker image
      docker_image:
        name: "mkurmanalieva/my-web-app:latest"
        source: pull

    - name: Run Docker container
      docker_container:
        name: mycontainer
        image: "mkurmanalieva/my-web-app:latest"
        ports:
          - "8080:8080"
        volumes:
          - /home/Web:/usr/local/apache2/htdocs/
        restart_policy: always
        state: started
      register: status

    - name: Check container status
      debug:
        var: status
