- name: Set up systemd service
  hosts: 192.168.97.129
  become: yes
  vars:
    app_port: 2222
    ansible_become_pass: meka

  tasks:
    - name: Copy application files
      copy:
        src: /Users/meerimkurmanalieva/Documents/DevOps/main.go
        dest: /home/mkurmanalieva/myapp/main.go
        mode: 0755

    - name: Build the Go application
      command: go build -o /home/mkurmanalieva/myapp/main /home/mkurmanalieva/myapp/main.go
      args:
        chdir: /home/mkurmanalieva/myapp

    - name: Copy systemd service file
      copy:
        src: /Users/meerimkurmanalieva/Desktop/Ansible/my_app.service.j2
        dest: /etc/systemd/system/my_app.service.j2
        mode: 0644

    - name: Start and enable the service
      systemd:
        name: my_app.service
        state: started
        enabled: yes
